site_name: Documentation Site Title
repo_name: wri/PUT_REPO_NAME_HERE
repo_url: https://github.com/wri/PUT_REPO_NAME_HERE
copyright: Copyright &copy; YEAR World Resources Institute

theme: 
  name: material
  custom_dir: overrides
  palette:
    scheme: default
    primary: white 
    accent: deep purple
  font: false
  language: en

markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.superfences
 
pages:
  - 'Home': 'index.md'


